config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'sign_up', to: 'home#new'
  post 'sign_up', to: 'home#create'
  get 'survey_forms/new' => 'survey_forms#new', as: 'new_survey'
  post 'survey_forms/new' => 'survey_forms#create', as: 'create_survey'
  resources :survey_forms
  get 'edit', to: 'home#edit'
  post 'edit', to: 'home#update'
  resources :home
  resources :questions
  get 'edit_ques', to: 'questions#edit'
  post 'edit_ques', to: 'questions#update', as: 'edit_quest'
  post 'questions/new' => 'questions#create', as: 'create_question'
  #get 'questions' => 'questions#edit', as: 'edit_questions'
  #get 'question/edit', to: 'question#edit', as: 'edi_question'
  #get 'managers' => 'home/roles' , as: 'view_manager'
  #get 'fill_form' ,to: 'survey_forms#fill_form/:id', as: 'fill_form'
  #get 'survey_form/fill_form/:id', to: 'survey_forms#fill_form', as: 'fill_form'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

end

app/models/survey_form.rb
class SurveyForm < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :survey_forms
  enum role: { HR: "HR", Employee: "Employee", Manager: "Manager" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :cnic, :role, :joining_date])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :cnic, :role, :joining_date])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # instantiates new user
  def index
    #@users = User.all
      @users = User.order(:first_name).page params[:page]
  end

  def show
  end

  def new
    @managers = User.where(role: "Manager")
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # stores saved user id in a session
      redirect_to root_path, notice: 'Successfully created account'
    else
      render :new
    end
  end

  def edit
    @managers = User.where(role: "Manager")
  end

  def update
    @managers = User.where(role: "Manager")
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: "Profile is successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def correct_user
    @user = User.find(params[:id])
  end

  def user_params
    # strong parameters
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :phone_number, :cnic, :role, :joining_date, :assigned_manager)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question , only:[:show,:edit,:update]
  def index
    @all_questions = Question.all
  end
  def new
    @new_question = Question.new
  end

  def create
    @new_question = Question.new(question_params)
    if @new_question.save
      redirect_to root_path ,notice:"Your Question has been successfully added"
    else
      render :new
    end
  end

  def show

  end


  def edit

  end

  def update

    if @question.update(question_params)
      redirect_to root_path, notice:"Your Question has been succesfully updated"
    else
      render :edit
    end

  end
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to root_path, notice: "Question is successfully removed from survey form"
  end

  private

  def question_params
    params.require(:question).permit(:questions)
  end


  def set_question
    @question = Question.find(params[:id])
  end


end

app/controllers/survey_forms_controller.rb
class SurveyFormsController < ApplicationController

  def new
    @questions_array = Question.pluck(:questions)
    @count = @questions_array.count
    @question = SurveyForm.new
    #Condition For HR

    if current_user.role == "HR"
      @quest = SurveyForm.find(params[:id])
      user = User.find(@quest.user_id)
      @quest = SurveyForm.where(user_id: user.id, submitted_by: user.email).last
      ud = User.find(SurveyForm.find(params[:id]).user.assigned_manager).email
      @managerquestion = SurveyForm.find_by(submitted_by: ud, user_id: @quest.user_id)
      @employee_answers =  @quest.quality.split(',')
      @manager_answers = @managerquestion.quality.split(',')
    elsif current_user.role == "Manager"

      @quest = SurveyForm.find(params[:id])
      @employee_answers =  @quest.quality.split(',')
    end
  end

  def show
    @question = SurveyForm.find(params[:id])
    if current_user.role == "Manager"
      ud = User.find(SurveyForm.find(params[:id]).user.assigned_manager).email
      @managerquestion = SurveyForm.find_by(submitted_by: ud, user_id: @question.user_id)
    else
      ud = User.find(SurveyForm.find(params[:id]).user.assigned_manager).email
      @managerquestion = SurveyForm.find_by(submitted_by: ud, user_id: @question.user_id)

      #GETTING HR REMARKS LOGIC
      dd = "ahsan.hr@engin.tech"
      @hrRemarks = SurveyForm.find_by(submitted_by: dd, user_id: @question.user_id)
    end
  end

  def create


    @employee_answers = []

    @questions_array = Question.pluck(:questions)

    @count = @questions_array.count


    if current_user.role != 'HR'
      @questions_array.each_with_index do |q ,i|
      @answer = @answer.to_s + params[:survey_forms]["answer-#{i}"] + ","
    end
    end

    @question = SurveyForm.new(survey_params.merge(quality: @answer))
    @user = User.find_by(id: survey_params[:user_id])

    if @question.save

      if current_user.role == "Employee"
        SurveyFormMailer.with(user: @user).survey_form_submission_email.deliver_now
      else
        SurveyFormMailer.with(user: @user).survey_form_to_hr.deliver_now
      end
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def survey_params
    params.require(:survey_forms).permit(:reliability, :job_knowledge, :attendence, :commitment, :creativity, :adherence_to_policy, :lead, :improvement_needed, :accomplishments, :user_id, :submitted_by, :remarks)
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationRecord
  has_secure_password
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.erb
<%= form_with model: @user, url: sign_up_path do |f| %>
    <div class="field from-group">
      <%= f.label :first_name %><br/>
      <%= f.text_field :first_name, autofocus: true %>
    </div>
    <div class="field from-group">
      <%= f.label :last_name %><br/>
      <%= f.text_field :last_name, autofocus: true %>
    </div>
    <div class="field from-group">
      <%= f.label :email %><br/>
      <%= f.email_field :email, autofocus: true %>
    </div>
    <div class="field from-group">
      <%= f.label :phone_number %><br/>
      <%= f.text_field :phone_number, autofocus: true %>
    </div>

    <div class="field from-group">
      <%= f.label :cnic %><br/>
      <%= f.text_field :cnic, autofocus: true %>
    </div>
    <div class="field from-group">
      <%= f.label :role %> <br>
      <%= f.select :role, ['Manager', 'Employee'] %> <br>
    </div>
    <div>
      <%= f.label :assigned_manager %><br/>
      <%= f.collection_select :assigned_manager, @managers, :id, :id, :prompt => true %>
    </div>
    <br>
    <%= f.label :joining_date %><br/>
    <%= f.date_select :joining_date, { :start_year => 1920, :end_year => 2050 }, :class => 'form-control date-select' %>
   <div class="field from-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br/>
      <%= f.password_field :password, autocomplete: "new-password" %>
   </div>

    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit class: "btn btn-primary " %>
    </div>
<% end %>

app/views/home/edit.html.erb
  <style>
      body {
          background: grey;
      }

      .form-control:focus {
          box-shadow: none;
          border-color: #BA68C8
      }

      .profile-button {
          background: rgb(99, 39, 120);
          box-shadow: none;
          border: none
      }

      .profile-button:hover {
          background: #682773
      }

      .profile-button:focus {
          background: #682773;
          box-shadow: none
      }

      .profile-button:active {
          background: #682773;
          box-shadow: none
      }

      .back:hover {
          color: #682773;
          cursor: pointer
      }

      .labels {
          font-size: 11px
      }

      .add-experience:hover {
          background: #BA68C8;
          color: #fff;
          cursor: pointer;
          border: solid 1px #BA68C8
      }
  </style>

<br>


<br>


<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
      <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold"><%= @user.first_name %></span><span class="text-black-50"><%= @user.email %></span><span> </span>
      </div>
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-right">Edit Employee</h4>
        </div>
        <%= form_with model: @user, url: edit_ques_path(id: @user.id), method: :post do |f| %>


          <div class="row mt-2">
            <div class="col-md-6">
              <div class="field from-group">
                <%= f.label :first_name %><br/>
                <%= f.text_field :first_name, autofocus: true %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="field from-group">
                <%= f.label :last_name %><br/>
                <%= f.text_field :last_name, autofocus: true %>
              </div>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-md-12">
              <div class="field from-group">
                <%= f.label :email %><br/>
                <%= f.email_field :email, autofocus: true %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="field from-group">
                <%= f.label :phone_number %><br/>
                <%= f.text_field :phone_number, autofocus: true %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="field from-group">
                <%= f.label :cnic %><br/>
                <%= f.text_field :cnic, autofocus: true %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="field from-group">
                <%= f.label :role %> <br>
                <%= f.select :role, ['Manager', 'Employee'] %> <br>

              </div>
            </div>
            <div class="col-md-12">
              <div>


                <%= f.label :assigned_manager %><br/>
                <%= f.collection_select :assigned_manager, @managers, :id, :id, :prompt => true %>


              </div>
            </div>
            <div class="col-md-12">
              <div>
                <%= f.label :joining_date %><br/>
                <%= f.date_select :joining_date, { :start_year => 1920, :end_year => 2050 }, :class => 'form-control date-select' %>
              </div>
            </div>

            <div class="mt-5 text-center">
              <div class="actions">
                <%= f.submit class: "btn btn-primary profile-button " %>
              </div>
            </div>

        <% end %>
        </div>
      </div>

    </div>
  </div>
</div>
</div>

app/views/home/roles/_employee.html.erb
<html>
<head>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

  <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>


  <style>


      .text {
          font-family: raleway;
          font-size: 40px;
          position: absolute center;
          text-align: center;
          padding-left: 0%;
          color: #000;
          margin-top: 43px;
      }

      .text1 {
          font-family: raleway;
          font-size: 21px;
          text-align: center;
          margin-top: -20px;
          color: #000;
      }

      .image {
          text-align: center;
          width: 200px;
          /* Container's dimensions */

          height: 200px;
          -webkit-border-radius: 75%;
          -moz-border-radius: 75%;
          box-shadow: 0 0 0 1px #eee;
          background: url("https://bootdey.com/img/Content/avatar/avatar7.png") center center no-repeat;
          background-size: cover;
          margin: auto;
          margin-top: 20px;
          margin-bottom: -30px;
          align-content: center;
      }


      .trick {
          display: inline-block;
          vertical-align: middle;
          height: 150px;
      }

      .image:hover {
          box-shadow: 0px 5px 20px .9px #3F3F3F;
      }

      .image:hover {
          -webkit-transform: scale(1.12);
          transform: scale(1.12);
          -webkit-transition: 1.6s ease-in-out;
          transition: 1.6s ease-in-out;
      }


      .trick:hover img {
          -webkit-transform: scale(1);
          transform: scale(1);
      }

      #overlay {
          -webkit-border-radius: 50%;
          -moz-border-radius: 50%;
          padding: 0 0 0 0;
          opacity: 1.0;
          -webkit-transition: opacity 2.25s ease;
          -moz-transition: opacity 10.25s ease;
      }

      #box:hover #overlay {
          opacity: 1;
      }


      .panel-group {
          width: 350px;
          margin: auto;
          /*margin:50px 400px 50px 400px;*/
          max-width: 100%;
      }

      .panel-heading {
          background-color: transparent !important;
      }

      .title {
          text-align: center;
          background-color: transparent;
          color: #000;
          font-family: lato;
          font-weight: 300;
          font-size: 15px;
          max-width: 100%;
      }


      #accordion {
          background-color: transparent;
          max-width: 100%;
          margin-bottom: 5px;
      }


      .btn-outline {
          color: inherit;
          transition: all 1.4s;
          background-color: transparent;
      }

      /* button CSS */

      .btn-danger.btn-outline {
          margin-top: 9px;
          background-color: transparent;
          color: #000;
          border-color: #000;
          padding: auto;
          padding: 10px 0px 10px 0px;
          margin: 1px 5px 1px 0px;
          width: 100%;
          text-align: center;
          font-family: raleway;
          font-weight: 300;
          max-width: 100%;
      }


      /*---------    Contact Form    ------------*/

      input::-webkit-input-placeholder,
      textarea::-webkit-input-placeholder {
          color: #000;
          font-size: 15px;
      }

      /* on hover placeholder */

      input:hover::-webkit-input-placeholder,
      textarea:hover::-webkit-input-placeholder {
          color: #fff;
          font-size: 15px;
          font-family: raleway;
      }

      input:hover:focus::-webkit-input-placeholder,
      textarea:hover:focus::-webkit-input-placeholder {
          color: #fff;
          font-family: raleway;
      }

      input:hover::-moz-placeholder,
      textarea:hover::-moz-placeholder {
          color: #fff;
          font-size: 15px;
          font-family: raleway;
      }

      input:hover:focus::-moz-placeholder,
      textarea:hover:focus::-moz-placeholder {
          color: #fff;
          font-family: raleway;
      }

      input:hover::placeholder,
      textarea:hover::placeholder {
          color: #fff;
          font-size: 15px;
          font-family: raleway;
      }

      input:hover:focus::placeholder,
      textarea:hover:focus::placeholder {
          color: #fff;
          font-family: raleway;
      }

      input:hover::placeholder,
      textarea:hover::placeholder {
          color: #fff;
          font-size: 15px;
          font-family: raleway;
      }

      input:hover:focus::-ms-placeholder,
      textarea:hover::focus:-ms-placeholder {
          color: #fff;
          font-family: raleway;
      }

      #form {
          position: relative;
          width: 100%;
          margin: 0px auto 0px auto;
          font-family: raleway;
      }

      input {
          font-family: raleway;
          font-size: 15px;
          width: 100%;
          height: 50px;
          padding: 0px 12px 0px 12px;
          background: transparent;
          outline: none;
          color: #726659;
          border: solid 1px #eee;
          border-bottom: none;
          transition: all 0.9s ease-in-out;
          -webkit-transition: all 0.9s ease-in-out;
          -moz-transition: all 0.9s ease-in-out;
          -ms-transition: all 0.9s ease-in-out;
      }

      input:hover {
          background: #ccc;
          color: #fff;
          font-family: raleway;
      }

      textarea {
          width: 100%;
          max-width: 100%;
          height: 110px;
          max-height: 110px;
          padding: 15px;
          background: transparent;
          outline: none;
          color: #000;
          font-family: raleway;
          font-size: 25px;
          border: solid 1px #eee;
          transition: all 0.9s ease-in-out;
          -webkit-transition: all 0.9s ease-in-out;
          -moz-transition: all 0.9s ease-in-out;
          -ms-transition: all 0.9s ease-in-out;
      }

      textarea:hover {
          background: #ccc;
          color: #fff;
          font-family: raleway;
      }

      #submit {
          width: 100%;
          padding: 0;
          font-family: raleway;
          font-size: 20px;
          color: #000;
          outline: none;
          cursor: pointer;
          border: solid 1px #eee;
          border-top: none;
          margin-bottom: 0px;
      }

      #submit:hover {
          color: #fff;
          background-color: #ccc;
      }

  </style>
</head>
<body>
<div class="box">
  <div id="overlay">
    <div class="image">
      <div class="trick">

      </div>
    </div>
    <ul class="text"><%= current_user.first_name %> <%= current_user.last_name %></ul>
    <div class="text1"><%= current_user.role %></div>

    <% if current_user.survey_forms.count >= 1 %>
      <% @abc = current_user.survey_forms[0] %>
      <%#= @abc %>
      <h1>Your Form Details</h1>
      <table  class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
        <tr>
          <th>Form Created At</th>
          <th>Submitted by</th>
          <th>Form Id</th>
          <th>View Form</th>
        </thead>
        <tbody>
        <tr>
          <td ><%= @abc.created_at %></td>
          <td ><%= current_user.email %></td>
          <td ><%= @abc.id %></td>
          <td><%= link_to 'Review Form', survey_form_path(id: @abc.id) %></td>
        </tr>
      </tbody>
      </table>
    <% else %>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading " role="tab" id="headingOne">
          <h4 class="panel-title ">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="" aria-controls="collapseOne">
              <div class="title  btn btn-danger btn-outline btn-lg">
                  <td><%= link_to 'Submit Form', new_survey_form_path %></td>
                <% end %>
              </div>
            </a>
          </h4>
        </div>

      </div>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
          <h4 style="text-align: center" class="panel-title">
            Form Status
          </h4>
        </div>

      </div>
    </div>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              <div class="title btn btn-danger btn-outline btn-lg">
                <% if current_user.survey_forms.count == 1 %>
                  <td><%= link_to 'Submitted By You', class: "badge badge-primary" %></td>
                <% elsif current_user.survey_forms.count == 2 %>
                  <td>
                  <td><%= link_to 'Submitted By you and Manager', class: "badge badge-secondary" %></td>
                  </td>
                <% elsif current_user.survey_forms.count == 3 %>
                  <% form_id = current_user.survey_forms[0].id %>
                  <td>
                  <td><%= link_to 'Status Completed', survey_form_path(id: form_id) %></td>
                  </td>
                <% else %>
                  <td>
                  <td><%= link_to 'Not Submitted By you' %></td>
                  </td>
                <% end %></div>
            </a>
          </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="panel-body">


            <form id="form" class="topBefore">

              <input id="name" type="text" placeholder="NAME">
              <input id="email" type="text" placeholder="E-MAIL">
              <textarea id="message" type="text" placeholder="MESSAGE"></textarea>
              <input id="submit" type="submit" value="Submit Now!">

            </form>


          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>





app/views/home/roles/_employee_table.html.erb
<table class="table table-striped table-borderless table-hover">
  <thead class="thead-dark">
  <tr>

    <th>Name</th>
    <th>Cnic</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Role</th>
    <th>Joining Date</th>
    <th>Manager Assigned</th>
    <th>Form Status</th>
    <th>Give Remark</th>
    <th></th>

  </tr>
  </thead>

  <tbody>

  <% @users.each do |employee| %>


    <tr>
      <% if employee.role == "Employee" %>

        <td><%= employee.first_name %>
          <%= employee.last_name %>
        </td>

        <td>  <%= employee.cnic %></td>
        <td><%= employee.email %><br></td>
        <td> <%= employee.phone_number %></td>
        <td><%= employee.role %></td>
        <td><%= employee.joining_date %></td>

        <% managers = User.find(employee.assigned_manager) %>
        <td><%= managers.first_name %> <%= managers.last_name %></td>

        <% if employee.survey_forms.any? %>
          <% @abc = employee.survey_forms[0].id %>
          <% @name = employee %>
          <td><%= link_to 'Submitted Form', survey_form_path(id: @abc) %></td>

        <% else %>
          <td><%= link_to 'Form Not Submiited' %></td>


        <% end %>



        <% if employee.survey_forms.count >= 3 %>
          <td><%= link_to 'Remarks Submitted' %></td>


        <% elsif employee.survey_forms.any? && employee.survey_forms.count > 1 %> %>
          <% @abc = employee.survey_forms[1].id %>
          <% @name = employee %>
          <td><%= link_to 'Give Remark', new_survey_path(id: @abc) %></td>
        <% else %>
          <td><%= link_to 'Form Not Submiited' %></td>


        <% end %>
        <td><%= link_to "Edit Employee", edit_home_path(employee.id) %></td>


      <% end %>


    </tr>
  <% end %>

  </tbody>

</table>

app/views/home/roles/_hr.html.erb
<style>
    .text {
        font-family: raleway;
        font-size: 40px;
        position: absolute center;
        text-align: center;
        padding-left: 0%;
        color: #000;
        margin-top: 43px;
    }
    .text1 {
        font-family: raleway;
        font-size: 21px;
        text-align: center;
        margin-top: -20px;
        color: #000;
    }
    .image {
        text-align: center;
        width: 200px;
        /* Container's dimensions */

        height: 200px;
        -webkit-border-radius: 75%;
        -moz-border-radius: 75%;
        box-shadow: 0 0 0 1px #eee;
        background: url("https://bootdey.com/img/Content/avatar/avatar7.png") center center no-repeat;
        background-size: cover;
        margin: auto;
        margin-top: 20px;
        margin-bottom: -30px;
        align-content: center;
    }
    .trick {
        display: inline-block;
        vertical-align: middle;
        height: 150px;
    }
    .image:hover {
        box-shadow: 0px 5px 20px .9px #3F3F3F;
    }
    .image:hover {
        -webkit-transform: scale(1.12);
        transform: scale(1.12);
        -webkit-transition: 1.6s ease-in-out;
        transition: 1.6s ease-in-out;
    }
    .trick:hover img {
        -webkit-transform: scale(1);
        transform: scale(1);
    }
    #overlay {
        -webkit-border-radius: 50%;
        -moz-border-radius: 50%;
        padding: 0 0 0 0;
        opacity: 1.0;
        -webkit-transition: opacity 2.25s ease;
        -moz-transition: opacity 10.25s ease;
    }
    #box:hover #overlay {
        opacity: 1;
    }
</style>

<div class="box">
  <div id="overlay">
    <div class="image">
      <div class="trick">
      </div>
    </div>
    <ul class="text"><%= current_user.first_name %> <%= current_user.last_name %></ul>
    <div class="text1"><%= current_user.role %></div>
  </div>
  <div>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">

      <li class="nav-item" role="presentation">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Managers</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Employees</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <%= render 'home/roles/manager_table' %>
      </div>
      <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        <%= render 'home/roles/employee_table' %>
      </div>
    </div>

























    <%= link_to 'Create Manager', sign_up_path, class: 'btn btn-outline-info' %>

  <%= link_to 'Create Question',new_question_path, class: 'btn btn-outline-info'%>
    <%= link_to 'View All Questions', questions_path, class: 'btn btn-outline-info' %>
  </div>

  <br>
</div>





app/views/questions/edit.html.erb
<%= form_with model: @question , url: edit_quest_path(id: @question.id), method: :post  do |f| %>
  <div class="field from-group">
    <%= f.label 'Enter the Question' %><br/>
    <%= f.text_field :questions, autofocus: true, required:true %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary " %>
  </div>
<% end %>

app/views/questions/index.html.erb
<h1> Hello World</h1>






<table class="table table-striped table-borderless table-hover">
  <thead class="thead-dark">
  <tr>


    <th>Question</th>
    <th></th>
    <th></th>


  </tr>
  </thead>

  <tbody>


  <% @all_questions.each do |question| %>


    <tr>
        <td><%= question.questions %></td>
      <td><%= link_to "Edit", edit_question_path(question.id) %></td>
      <td><%= link_to "Delete", question_path(question.id) , :confirm => "Are you sure?", :method => :delete%></td>


    </tr>
  <% end %>



  </tbody>

</table>